jumps: 86400
start_date: "2017-08-17"
end_date: "2025-12-05"
root: "./data"
date_format: "%Y-%m-%d"
data_path: "./data/binance_processed.csv"
train_interval: ["2017-08-17", "2023-12-15"]
val_interval: ["2023-12-15", "2024-12-15"]
test_interval: ["2024-12-15", "2025-12-05"]
additional_features: []
