data_config: 'binance_full'
model: 'CMamba_v2'

name: 'CMamba_Binance'
max_epochs: 1000
use_volume: True
additional_features: []

hyperparams:
    optimizer: 'adam'
    lr: 0.01
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.001
