data_config: 'binance_full'
model: 'iTransformer_v'

name: 'itransformer'
max_epochs: 1000
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.002
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001