data_config: 'binance_full'
model: 'LinearCrypto_nv'

name: 'LinearCrypto_nv'
max_epochs: 300
use_volume: False

hyperparams:
    optimizer: 'adam'
    lr: 0.001
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.0001
