data_config: 'binance_full'
model: 'LinearCrypto'

name: 'LinearCrypto'
max_epochs: 1500
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.001
    lr_step_size: 100
    lr_gamma: 0.75
    weight_decay: 0.0001
