data_config: 'binance_full'
model: 'LSTM_v'

name: 'lstm'
max_epochs: 700
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.0001
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001